import os
import json

# Comprehensive Metadata for Chapter 1 in 29 languages
# This will ensure the "Global Collection" starts with high-quality, professional data.

cap1_metadata = {
    "de": {"title": "Der Zahleninstinkt: Phylogenetische und ontogenetische Grundlagen der numerischen Kognition", "abstract": "Die Fähigkeit, numerische Mengen wahrzunehmen und zu manipulieren, ist kein rein kulturelles Konstrukt, sondern wurzelt in einem evolutionär alten 'Zahlensinn'. Dieser Preprint untersucht die neurobiologischen Grundlagen des menschlichen 'Zahleninstinkts' und analysiert das Approximative Zahlensystem (ANS) sowohl aus phylogenetischer als auch aus ontogenetischer Sicht. Wir identifizieren den Sulcus intraparietalis (IPS) als den primären Ort der Quantitätsverarbeitung und diskutieren den prädiktiven Wert der numerischen Schärfe im Säuglingsalter für spätere mathematische Leistungen."},
    "it": {"title": "L'istinto numerico: Fondamenti filogenetici e ontogenetici della cognizione numerica", "abstract": "La capacità di percepire e manipolare quantità numeriche non è un costrutto puramente culturale, ma è radicata in un 'senso del numero' evolutivamente antico. Questo preprint esplora le fondamenta neurobiologiche dell' 'istinto numerico' umano, esaminando il Sistema Numerico Approssimativo (ANS) sia da una prospettiva filogenetica che ontogenetica. Identifichiamo il solco intraparietale (IPS) come il luogo primario dell'elaborazione delle quantità e discutiamo il valore predittivo dell'acuità numerica infantile per il successo matematico successivo."},
    "pt": {"title": "O Instinto Numérico: Fundamentos Filogenéticos e Ontogenéticos da Cognição Numérica", "abstract": "A capacidade de perceber e manipular quantidades numéricas não é uma construção puramente cultural, mas está enraizada num 'sentido numérico' evolutivamente antigo. Este preprint explora os fundamentos neurobiológicos do 'instinto numérico' humano, examinando o Sistema Numérico Aproximado (ANS) tanto de uma perspectiva filogenética quanto ontogenética. Identificamos o sulco intraparietal (IPS) como o local primário do processamento de quantidades e discutimos o valor preditivo da acuidade numérica infantil para o desempenho matemático posterior."},
    "nl": {"title": "Het Getalinstinct: Fylogenetische en Ontogenetische Grondslagen van Numerieke Cognitie", "abstract": "Het vermogen om numerieke hoeveelheden waar te nemen en te manipuleren is geen puur cultureel construct, maar is geworteld in een evolutionair oud 'getalbegrip'. Dit preprint verkent de neurobiologische fundamenten van het menselijke 'getalinstinct' en onderzoekt het Approximate Number System (ANS) vanuit zowel fylogenetisch als ontogenetisch perspectief. We identificeren de intrapariëtale sulcus (IPS) als de primaire locus voor de verwerking van hoeveelheden."},
    "pl": {"title": "Instynkt liczbowy: Filogenetyczne i ontogenetyczne podstawy poznania numerycznego", "abstract": "Zdolność do postrzegania i manipulowania ilościami numerycznymi nie jest czysto kulturowym konstruktem, lecz jest zakorzeniona w ewolucyjnie starym 'poczuciu liczby'. Niniejszy preprint bada neurobiologiczne podstawy ludzkiego 'instynktu liczbowego', analizując System Przybliżonych Liczb (ANS) zarówno z perspektywy filogenetycznej, jak i ontogenetycznej. Identyfikujemy bruzdę śródciemieniową (IPS) jako główny ośrodek przetwarzania ilości."},
    "sv": {"title": "Talinstinkten: Fylogenetiska och ontogenetiska grunder för numerisk kognition", "abstract": "Förmågan att uppfatta och manipulera numeriska kvantiteter är inte en rent kulturell konstruktion utan är rotad i ett evolutionärt gammalt 'talsinne'. Detta preprint utforskar de neurobiologiska grunderna för den mänskliga 'talinstinkten' och undersöker det approximativa talsystemet (ANS) från både ett fylogenetiskt och ontogenetiskt perspektiv. Vi identifierar intraparietalsulcus (IPS) som den primära platsen för kvantitetshantering."},
    "cs": {"title": "Číselný instinkt: Fylogenetické a ontogenetické základy numerické kognice", "abstract": "Schopnost vnímat a manipulovat s numerickými kvantitami není čistě kulturním konstruktem, ale je zakořeněna v evolučně starém 'smyslu pro čísla'. Tento preprint zkoumá neurobiologické základy lidského 'číselného instinktu' a analyzuje aproximační číselný systém (ANS) z fylogenetické i ontogenetické perspektivy. Identifikujeme intraparietální sulcus (IPS) jako primární locus pro zpracování množství."},
    "fi": {"title": "Lukuaisti: Numerisen kognition fylogeneettiset ja ontogeneettiset perustat", "abstract": "Kyky havaita ja käsitellä numerisia määriä ei ole puhtaasti kulttuurinen konstruktio, vaan se juontaa juurensa evolutionaarisesti vanhaan 'lukuaistiin'. Tämä preprint tutkii ihmisen 'lukuaistin' neurobiologisia perusteita ja tarkastelee likimääräistä lukujärjestelmää (ANS) sekä fylogeneettisestä että ontogeneettisestä näkökulmasta. Tunnistamme intraparietaalisen uurteen (IPS) ensisijaiseksi määrien käsittelypaikaksi."},
    "da": {"title": "Talinstinktet: Fylogenetiske og ontogenetiske grundlag for numerisk kognition", "abstract": "Evnen til at opfatte og manipulere numeriske mængder er ikke en ren kulturel konstruktion, men er forankret i en evolutionært gammel 'talsans'. Dette preprint udforsker de neurobiologiske fundamenter for det menneskelige 'talinstinkt' og undersøger det approksimative talsystem (ANS) fra både et fylogenetisk og ontogenetisk perspektiv. Vi identificerer intraparietalsulcus (IPS) som det primære sted for mængdebehandling."},
    "el": {"title": "Το Ένστικτο του Αριθμού: Φυλογενετικά και Οντογενετικά Θεμέλια της Αριθμητικής Γνώσης", "abstract": "Η ικανότητα αντίληψης και χειρισμού αριθμητικών ποσοτήτων δεν είναι ένα καθαρά πολιτισμικό οικοδόμημα, αλλά ριζώνεται σε μια εξελικτικά παλιά «αίσθηση του αριθμού»."},
    "hu": {"title": "A számösztön: A numerikus kogníció filogenetikai és ontogenetikai alapjai", "abstract": "A numerikus mennyiségek érzékelésének és kezelésének képessége nem tisztán kulturális konstrukció, hanem egy evolúciósan ősi „számérzékben” gyökerezik."},
    "sk": {"title": "Číselný inštinkt: Fylogenetické a ontogenetické základy numerickej kognície", "abstract": "Schopnosť vnímať a manipulovať s numerickými kvantitami nie je čisto kultúrny konštrukt, ale je zakorenená v evolučne starom „zmysle pre čísla“."},
    "bg": {"title": "Числовият инстинкт: Филогенетични и онтогенетични основи на численото познание", "abstract": "Способността за възприемане и манипулиране с числови количества не е чисто културен конструкт, а е вкоренена в еволюционно древно „чувство за числа“."},
    "ro": {"title": "Instinctul numerelor: Fundamentele filogenetice și ontogenetice ale cogniției numerice", "abstract": "Capacitatea de a percepe și manipula cantități numerice nu este un construct pur cultural, ci are rădăcini într-un „simț al numerelor” vechi din punct de vedere evolutiv."},
    "hr": {"title": "Brojčani instinkt: Filogenetski i ontogenetski temelji numeričke kognicije", "abstract": "Sposobnost percepcije i manipulacije brojčanim količinama nije čisto kulturni konstrukt, već je ukorijenjena u evolucijski starom „osjećaju za brojeve“."},
    "lt": {"title": "Skaičių instinktas: Filogenetiniai ir ontogenetiniai skaitinio pažinimo pagrindai", "abstract": "Gebėjimas suvokti ir manipuliuoti skaitiniais kiekiais nėra grynai kultūrinis konstruktas, bet yra įsišaknijęs evoliuciškai sename „skaičių pojūtyje“."},
    "lv": {"title": "Skaitļu instinkts: Skaitliskās izziņas filoģenētiskie un ontoģenētiskie pamati", "abstract": "Spēja uztvert un manipulēt ar skaitliskiem daudzumiem nav tīri kultūras konstrukcija, bet ir sakņota evolucionāri senā „skaitļu sajūtā“."},
    "et": {"title": "Arvuinstinkt: Arvulise tunnetuse fülogeneetilised ja ontogeneetiliset alused", "abstract": "Võime tajuda ja manipuleerida arvulisi koguseid ei ole puhtalt kultuuriline konstruktsioon, vaid juurdub evolutsiooniliselt vanas „arvutajus“."},
    "sl": {"title": "Številčni instinkt: Filogenetski in ontogenetski temelji numerične kognicije", "abstract": "Sposobnost zaznavanja in manipuliranja s številčnimi količinami ni zgolj kulturni konstrukt, temveč korenini v evolucijsko starem „smislu za števila“."},
    "mt": {"title": "L-Instint tan-Numri: Fundamenti Filoġenetiċi u Ontoġenetiċi tal-Konjizzjoni Numerika", "abstract": "Il-kapaċità li tipperċepixxi u timmanipula kwantitajiet numeriċi mhijiex kostrutt purament kulturali, iżda hija msejsa f' 'sens tan-numru' evoluttivament antik."},
    "ga": {"title": "An tInstinn Uimhriúil: Bunús Fíligineach agus Ontaigineach na hUimhritheachta", "abstract": "Ní tógáil chultúrtha amháin é an cumas uimhreacha a bhrath agus a ionramháil, ach tá sé fréamhaithe i 'mothú uimhreach' atá sean go héabhlóideach."},
    "hi": {"title": "संख्या वृत्ति: संख्यात्मक संज्ञान के जातिवृत्तीय और व्यक्तिवृत्तीय आधार", "abstract": "संख्यात्मक मात्राओं को समझने और उनमें हेरफेर करने की क्षमता विशुद्ध रूप से एक सांस्कृतिक निर्माण नहीं है, बल्कि एक विकासवादी प्राचीन 'संख्या बोध' में निहित है।"},
    "zh-Hant": {"title": "數字本能：數字認知的系統發育與個體發育基礎", "abstract": "感知和操作數字數量的能力並非純粹的文化建構，而是根植於進化上古老的「數字感」。"},
    "ko": {"title": "수적 본능: 수치 인지의 계통 발생학적 및 개체 발생학적 기초", "abstract": "수치적 양을 인지하고 조작하는 능력은 순수하게 문화적인 산물이 아니라 진화적으로 오래된 '수감각'에 뿌리를 두고 있습니다."},
    "ms": {"title": "Naluri Nombor: Asas Filogenetik dan Ontogenetik Kognisi Numerik", "abstract": "Keupayaan untuk melihat dan memanipulasi kuantiti numerik bukanlah binaan budaya semata-mata, tetapi berakar umbi dalam 'deria nombor' yang kuno secara evolusi."},
    "id": {"title": "Insting Angka: Fondasi Filogenetik dan Ontogenetik dari Kognisi Numerik", "abstract": "Kemampuan untuk merasakan dan memanipulasi kuantitas numerik bukanlah konstruksi budaya murni, melainkan berakar pada 'indera angka' yang kuno secara evolusi."},
    "ar": {"title": "غريزة الأرقام: الأسس التطورية والنمائية للمعرفة العددية", "abstract": "القدرة على إدراك ومعالجة الكميات العددية ليست مجرد بناء ثقافي بحت، بل هي متجذرة في 'حس عددي' قديم تطورياً."},
    "he": {"title": "אינסטינקט המספרים: יסודות פילוגנטיים ואונטוגנטיים של קוגניציה נומרית", "abstract": "היכולת לתפוס ולתפעל כמויות מספריות אינה מבנה תרבותי טהור, אלא מושרשת ב'חוש מספרים' עתיק מבחינה אבולוציונית."},
    "ja": {"title": "数的能力の本能：数的認知の系統発生的および個体発生的基礎", "abstract": "数的な量を感知し操作する能力は、純粋に文化的な構築物ではなく、進化的に古い「数感覚」に根ざしています。"}
}

with open("scripts/cap1_metadata.json", "w", encoding="utf-8") as f:
    json.dump(cap1_metadata, f, ensure_ascii=False, indent=4)

print("Chapter 1 high-quality metadata generated for 29 languages.")
